# Stage 1: Build stage
FROM node:20.11-alpine as builder

WORKDIR /app

COPY package*.json ./
COPY ./web/package*.json ./web/

RUN npm ci

COPY ./web ./web

RUN npm run build -w web

# Stage 2: Production-ready stage
FROM node:20.11-alpine

ARG COMMIT_HASH
ENV COMMIT_HASH=$COMMIT_HASH

WORKDIR /app

# Copy only the necessary files from the build stage
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/web/package*.json ./web/

COPY --from=builder /app/web/.next ./web/.next

RUN npm ci --only=production

EXPOSE 3000

CMD [ "npm", "run", "start","-w", "web"]
