# Base image
FROM node:20.11-alpine

ARG COMMIT_HASH
ENV COMMIT_HASH=$COMMIT_HASH

# Set working directory
WORKDIR /app

# Install dependencies
COPY ./web/package*.json ./

RUN npm install

# Copy application source code
COPY ./web ./

# Expose the application port (change it if needed)
EXPOSE 3000

# Run the application
CMD ["npm", "run", "dev"]
